export class LKPTitles {
    public static Equipment = "Instrument";
    public static Materials = "Materials";
    public static testParameter = "Test/Parameter Name";
    public static actions = "Actions";
    public static actionsBy = "Users";
    public static Vendor = "Vendor";
    public static ThirdParty = "Third Party";
    public static siteAddress = "Site Address";
    public static auditors = "Auditors";
    public static auditDoc = "Audit Document";
    public static CheckList = "Audit CheckList";
    public static Customer = "Customer Name";
    public static Auditee = "Auditee";
    public static product = "Products";
    public static specifications = "Specifications";
    public static BatchNumber = "Batch Number";
    public static status = "Status";
    public static invalidation = "Invalidation";
    public static invalidationCode = "System Code";
    public static solution = "Solutions";
    public static solutionName = "Solution Name"
    public static regent = "Chemical";
    public static psMaterials = "Primary Standard Material";
    public static indicatorCode = "System Code";
    public static Chemical = "Chemical";
    public static analyst = "Analyst";
    public static planCreated = "Plan Created By";
    public static sampleTitle = "Sampling";
    public static wetInstrTitle = "Samples Analysis";
    public static manualActTitle = "Manual Activity Type";
    public static samplePlan = "Work Allotment";
    public static requCodeFrom = "Request Code From";
    public static reqCodeTo = "Request Code To";
    public static sampleNumber = "Sample Numbers";
    public static batchNumber = "Lot/Batch Numbers";
    public static projects = "Projects";
    public static arNumber = "AR Numbers";
    public static arNumberAndRef = "AR Number / Reference Number"
    public static testName = "Parameter Name";
    public static parameter = "Parameter";
    public static inventory = "Inventory";
    public static component = "Component";
    public static DestructionNo = "Request Code";
    public static technique = "Techniques";
    public static refArNumber = "AR Numbers";
    public static analysisInstrTitle = "Instrument ID";
    public static columnIDs = "Column ID's";
    public static plannedChange = "Planned Change Numbers";
    public static deviationNum = "Deviation Numbers";
    public static changeControl = "CCR Numbers";
    public static initProc = "IP Numbers";
    public static capa = "CAPA Numbers";
    public static initiatedBy = "Analyst / Initiated By"

    public static instrumentType = "Instrument Type";
    public static instrument = "Instrument";
    public static category = "Category";
    public static subcategory = "Sub Category";
    public static sdms = "SDMS Details";

    public static calibration = "Calibration Parameter Set";

    public static calibrationRef = "Calibration Reference";

    public static stdProcedure = "Standard Test Procedure";
    public static test = "Test Name";
    public static equipmentID = "Equipment/ Instrument Title / ID";
    public static calibParameterGroup = "Select Parameter Group"
    public static calibSubGroup = "Select Sub Group";
    public static calibParameter = "Select Parameter Name";
    public static calibInstr = "Instrument";
    public static refNum = "Reference Number";
    public static manufacturer = "Manufacturers";
    public static mobilePhase = "Mobile Phase";

    public static systemCodeFrom = "System Code From";
    public static systemCodeTo = "System Code To";
    public static createdBy = "Request Created By";

    public static formula = "Formulae";
    public static Documents = "Documents";
    public static analysisDone = "Analysis Done By";
    public static chemicalSol = "Chemical/Solution"
    public static systemCode = "System Code";
    public static materialsSolu = "Materials/Solutions";
    public static inwardNumbers = "Inward Numbers";
    public static initUser = "Intiated By";
    public static dataReview = "Data Review";
    public static oos = "Out of Specification";
    public static calib = "Calibrations";
    public static parameterSetNumber = "Parameter Set Number";
    public static maintenanceSchedule = "Calibration Schedule";
    public static maintenanceEquipments = "Maintenance Equipments";
    public static refEqpOcc = "Refer Instrument Occupancy";
    public static eqpOrInstID = "Equipment/Instrument ID";
}

export class LKPDisplayNames {
    public static Status = "Status";
    public static StatusCode = "Status Code";
    public static action = "Action";
    public static actionCode = "Action Code";
    public static actionBy = "User Name";
    public static actionByCode = "User Code";
    public static dept = "Primary Dept."
    public static designation = "Designation";
    public static reservedQty = "Reserved Qty.";

    public static product = "Product Name";
    public static productCode = "Product Code";
    public static specNumber = "Specification Number";
    public static specification = "Specification Title";
    public static batchNumber = "Batch Number";
    public static inwardNumber = "Inward Number";
    public static batchStatus = "Status";
    public static Material = "Material Name";
    public static MaterialCode = "Material Code";
    //public static testCode = "Test Code";
    public static EquipmentMP = "Instrument Title";
    public static EquipmentCodeMP = "Instrument ID";
    public static Equipment = "Instrument Title";
    public static EquipmentCode = "Instrument ID";
    public static InvalidationNumber = "Invalidation Number";
    public static InvalidationCode = "System Code";
    public static reagent = "Name of the Chemical";
    public static reagentCode = "Chemical Code";
    public static psMaterial = "PS Material";
    public static psMaterialCode = "PS Material Code";
    public static Indicator = "Solution";
    public static IndicatorCode = "System Code";
    public static solution = "Solution";
    public static solutionName = "Solution Name";
    public static Chemical = "Name of the Chemical";
    public static ChemicalCode = "Chemical Code";
    public static stpNumber = 'STP Ref. Number';
    public static sampleActivityName = "Test Name";
    public static sampleActivityCode = "AR Number";
    public static samplingActivityName = "Assigned User";
    public static samplingActivityCode = "Ar Number";
    public static manualActivityName = "Manual Activity Name";
    public static manualActivityCode = "Manual Activity Code";
    public static samplePlanCode = "Work Allotment Code";
    public static reqCodeFromDate = "Request Code From";
    public static reqCodeToDate = "Request Code To";
    public static sampleNumber = "Sample Number";
    public static mrrBatchNumber = "Lot/Batch No.";
    public static block = "Block";
    public static smapleInward = "Sample Inward No.";
    public static arNumber = "AR Numbers";
    public static projectCode = "Project Code";
    public static project = "Project Name";
    public static test = "Parameter Name";
    public static parameterID = "Parameter ID";
    public static srNum = "S.No.";
    public static description = "Test/parameter";
    public static parameter = "Parameter Name";
    public static packNo = "Pack No.";
    public static material = "Material";
    public static testParName = "Test/Parameter";
    public static techniqueCode = "Technique Code";
    public static techniqueName = "Technique Name";
    public static analystCode = "Employee ID";
    public static planCreatedID = "Plan Created By ID";
    public static analystName = "Employee Name";
    public static planCreatedBy = "Plan Created By Name";
    public static solutionCode = "Solution Short Name/Code";
    public static solutionShortName = "Short Name / Code";
    public static remQty = "Available Qty.";
    public static component = "Component";
    public static componentCode = "Component Code";
    public static destructionCode = "Request Code";
    public static destructionName = "Source";
    public static analysisOccuCode = "Instrument ID";
    public static analysisOccuName = "Instrument Title";
    public static testCode = "Parameter ID";

    public static reportID = "Reference Number";
    public static status = "Status";

    public static analysisColumnCode = "Equipment / Instrument ID";
    public static analysisColumnName = "Equipment / Instrument Title";

    public static department = "Requested Department";
    public static pcNumber = "PC Number";
    public static devNumber = "Deviation Number";
    public static ccNumber = "CC Number";
    public static productTitle = "Product/Title";
    public static ipNumber = "IP Number";
    public static source = "Source";
    public static capaNum = "CAPA Number";
    public static sourceRef = "Source Reference";

    public static instrumentType = "Instrument Type";
    public static instrumentTypeCode = "Instrument Type Code";
    public static equipmentCode = "Equipment/Instrument Code";
    public static equipmentID = "Equipments/ Instruments Id";
    public static equipmentTitle = "Equipment/Instrument Title";

    public static instrumentName = "Instrument";
    public static instrumentCode = "Instrument Code";

    public static sno = "S.No.";
    public static category = "Group";


    public static subCategory = "Sub Group";
    public static sdmsTitle = "Report Title";
    public static sdmsCode = "Received Date";
    public static prepRunNo = "Prep. Run No - File Name";
    public static templateNo = "Template No. / Version";
    public static stpTitle = "STP Title";
    public static testName = "Test Name";

    public static testPaCode = "TestCode";
    public static testID = "Test ID";
    public static calibrationParameter = "Calibration";
    public static calibCode = "Calibration Code";
    public static calibInTitle = "Title";
    public static requestCode = "Request Code";
    public static systemCode = "System Code";
    public static manufacturerCode = "Manufactuerer Code";
    public static manufacturer = "Manufacturer";
    public static mobilePhase = "System Code";
    public static batchNum = "Batch Number";
    public static customerCode = "Customer Code";
    public static customer = "Customer Name";

    public static formulaTitle = "Formula Title";
    public static formulaDef = "Formula Defination";

    public static DocNo = "Doc. No ( Ver. No )";
    public static DocName = "Doc. Name";

    public static materialSolu = "Material/Solution";
    public static MaterialSoluCode = "Material/Solution Code";

    public static dataReview = "Data Review Code";
    public static requestType = "Request Type"

    public static oosCode = "OOS Code";
    public static availQty = "Available Qty.";
    public static parameterSetCode = "Parameter Set Code";
    public static employeeCode = "Employee Code";
    public static employeeName = "Employee Name";
    public static scheduleNumber = "Schedule Number";
    public static scheduleType = "Schedule Type";
    public static equipmentUserCode = "Equipment Code";
    public static equipmenTitle = "Equipment Title";
    public static occSource = "Occupancy Source";
    public static entRefNumber = "Entity Reference Number";
    public static refInvBatch = "Reference Batch Number";
    public static testOrParameterName = "Test/Parameter Name";
    public static testOrParameterID = "Test/Parameter ID";
}

export class LKPPlaceholders {
    public static action = "Action";
    public static actionBy = "Action By";
    public static Status = "Status";
    public static product = "Product Name / Material Name";
    public static specification = "Specification Number";
    public static Material = "Material / Product Name";
    public static materialID = "Material ID";
    public static lkpMaterial = "Material";
    public static promaterial = "Product / Material Name";
    public static testParamName = "Test/Parameter Name";
    public static BatchNumber = "Batch Number";
    public static Equipment = "Instrument";
    public static Invalidation = "Invalidation";
    public static Referencecode = "System Code";
    public static nameOfTheSolMaterial = "Name of the solution";
    public static reagent = "Name of the Chemical";
    public static psMaterial = "PS Material";
    public static indicatorCode = "System Code";
    public static solution = "Solution";
    public static solutionName = "Solution Name";
    public static Chemical = "Name of the Chemical";
    public static analyst = "Analyst Name";
    public static initiatedBy = "Analyst / Initiated By"
    public static planCreatedBy = "Plan Created By";
    public static sampleActivity = "Samples Analysis";
    public static samplingActivity = "Sampling";
    public static manualActivity = "Manual Activity Type";
    public static samplePlan = "Work Allotment";
    public static reqCodeFrom = "Request Code From";
    public static reqCodeTo = "Request Code To";
    public static SampleNumber = "Sample / Operation Number";
    public static batchNumber = "Lot / Batch Number";
    public static arNumber = "AR Number / Reference Number";
    public static project = "Project";
    public static test = "Parameter Name";
    public static parameter = "Parameter Name";
    public static component = "Component";
    public static destructionNo = "Request Code"
    public static qcInvtChemical = "Chemicals"
    public static inventory = "Inventory";
    public static technique = "Technique";
    public static refArNumber = "AR Number";
    public static analysisOccu = "Instrument ID";
    public static analysisColumnIDOccu = "Column ID";
    public static number = "Number";
    public static instrumentType = "Instrument Type";
    public static instrument = "Instrument";
    public static category = "Category";
    public static subCategory = "Sub Category";
    public static sdms = "SDMS Details";
    public static calibration = "Calibrate Instrument ID";
    public static stpTitle = "STP Title";
    public static stpNumber = "STP Number";
    public static calibrationRef = "Calibration Reference";
    public static testName = "Test Name";
    public static samplerID = "Sampler ID";
    public static equipmentID = "Equipment/ Instrument Title / ID";
    public static calibrationParam = "Calibration";
    public static calibParameterGroup = "Select Parameter Group"
    public static calibSubGroup = "Select Sub Group";
    public static calibParameter = "Select Parameter Name";
    public static calibInstr = "Instrument";
    public static calibParam = "Parameter";
    public static refNum = "Reference Number";
    public static calibSystemCode = "System Code";
    public static manufacturer = "Manufacturer";
    public static mobilePhase = "Mobile Phase";
    public static responsibility = "Responsibility";
    public static customer = "Customer";
    public static systemCodeFrom = "System Code From";
    public static systemCodeTo = "System Code To";
    public static createdBy = "Request Created By";
    public static caliRefNumber = "Calibration Reference No.";
    public static paraSetRefNumber = "Parameter Set Reference Number";
    public static formula = "Formulae";
    public static Documents = "Documents";
    public static analysisDone = "Analysis Done By";
    public static chemicalSol = "Chemical/Solution Name"
    public static matSolution = "Material/Product Name/Solution Name"
    public static inwardNumbers = "Inward Numbers";
    public static initUser = "Initiated By";
    public static dataReview = "Data Review";
    public static oos = "Out of Specification";
    public static materialCode = "Material Code";
    public static parameterSetNumber = "Parameter Set Number";
    public static productName = "Product Name";
    public static maintenanceSchedule = "Calibration Schedule";
    public static maintenanceequipment = "Equipment/Instrument ID";
    public static refEqpOcc = "Refer Instrument Occupancy";

}

export class LkpPurpose {
    public static Calb = "CALB";
    public static LogEntry = "LOG_ENTRY";
    public static FilterBag = "FILTERBAG";
    public static Cartridge = "CARTRIDGE";
    public static ReceiverTank = "RECEIVERTANK";
}